# -*- coding: utf-8 -*-
"""Python_labs_Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m2g9jMEIlSdm5MpQqSGNuV2jKzT2EDwA

When we use here _install + "packagename"_ we don't use conda install in colab

# Review Functions
"""

# Read line function and retur 
def printline(my_path, my_option):
  """
  This function read the file content and
  return it according to bulk option.
  """

  with open(my_path, "r") as f:
    if  my_option == 'B': # if bulk option is specified
      lines = f.read() # read the whole text
      f.close() # close it open
    else: # read line by line 
      lines = f.readlines()
      f.close() # close open
  return lines

# to see the path
#pwd

# declare the path
input_path = "/Users/elhadji/Desktop/Python_Labs/test.txt"

# call the function 
printline(input_path, 'B')

"""Use try ... except now """

# Read line function and retur 
def printline2(my_path, my_option):
  """
  This function read the file content and
  return it according to bulk option.
  If the file does not exist, the raise the error.
  """
  try:
    with open(my_path, "r") as f:
      if  my_option == 'B': # if bulk option is specified, read the whole text
        lines = f.read() # read the whole content once
        f.close() # close it open
      else: # read line by line 
        lines = f.readlines() # read line by line
        f.close() # close open
      return lines

  except FileNotFoundError:
    lines = 'No such file'
    print("File not found, chek the name !") # raise the error
    return lines

# call the function with correct path
printline2(input_path, 'K')

# call function with inccorrect path
path_error = "/content/test.txt0"
printline2(path_error, 'B')

